site_name: Pymagnet

theme:
  name: material

nav:
  - Home: index.md
  - Examples: examples.md
  - Magnets:
      - Overview: magnets/magnets_overview.md
      - 1D Methods: magnets/magnets_1d.md
      - 2D Magnets: magnets/magnets_2d.md
      - 3D Magnets: magnets/magnets_3d.md
      - Composite Magnets: magnets/composite_magnets.md
  - Plots:
      - Overview: plots/plots_overview.md
      - 2D Plots: plots/plots_2d.md
      - 3D Plots: plots/plots_3d.md
  - Forces & Torques: forces_torques.md
  - Methods:
      - Class Methods: methods/methods.md
      - Transforms: methods/transforms.md
  - Code Reference:
      - pymagnet: code_reference/pymagnet.md
      - magnets: code_reference/magnets.md
      - plots: code_reference/plots.md
      - utils: code_reference/utils.md

plugins:
  - search
  - mermaid2
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
