{% set name = "pymagnet" %}
{% set version = "0.3.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a23a5bbd484966c2156551483f96a273216b68dde3cfb6ec364e205359f4d2e0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - numba
    - numpy
    - numpy-stl
    - pip
    - plotly
    - python
  run:
    - matplotlib
    - numba
    - numpy
    - numpy-stl
    - plotly
    - python

test:
  imports:
    - pymagnet
    - pymagnet.forces
    - pymagnet.magnets
    - pymagnet.plots
    - pymagnet.utils

about:
  home: "https://github.com/pdunne/pymagnet"
  license: "Mozilla Public 2.0 (MPL 2.0)"
  license_family: MOZILLA
  license_file: LICENSE
  summary: "User Friendly Magnetic Field Calculations"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
